image:
  repository: kong/kong-gateway
  tag: "3.4"

secretVolumes:
  - kong-cluster-cert
  - kong-ca-cert

env:
  role: data_plane
  database: "off"
  status_listen: 0.0.0.0:8100
  cluster_control_plane: kong-cp-kong-cluster.kong-cp.svc.cluster.local:443
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong-cp.svc.cluster.local:443
  cluster_mtls: pki
  cluster_server_name: kong-cp-kong-cluster.kong-cp.svc.cluster.local
  cluster_telemetry_server_name: kong-cp-kong-clustertelemetry.kong-cp.svc.cluster.local
  lua_ssl_verify_depth: 3
  cluster_ca_cert: /etc/secrets/kong-ca-cert/ca.crt
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key


ingressController:
  enabled: false

admin:
  enabled: false

manager:
  enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

proxy:
  enabled: true
  type: LoadBalancer
  annotations: {}
  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443
    parameters:
      - http2
  ingress:
    enabled: true